lightning:
  # ... other settings ...
  trainer:
    benchmark: True
    max_steps: 6100
    gpus: 1
    max_epochs: 100
    precision: 16
    # Add these settings for progress bar
    progress_bar_refresh_rate: 1
    weights_summary: "top"
    profiler: "simple"
    log_every_n_steps: 1

  callbacks:
    progress_bar:
      target: pytorch_lightning.callbacks.TQDMProgressBar
      params:
        refresh_rate: 1
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 200
        max_images: 8
        increase_log_steps: False
